version: '3.5'

services:
  restaurantlisting_db:
    image: mysql:latest
    volumes:
      - database_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurantlisting
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: unless-stopped
    ports:
      - "127.0.0.1:3333:3333"

volumes:
  database_mysql: