version: '3.5'

services:
  restaurantlisting_db:
    container_name: restaurantlisting_db
    image: mysql:latest
    volumes:
      - "./data:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurantlisting
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: unless-stopped
    ports:
      - "3308:3306"

